### ISSUE TITLE
Can not find PaymentData.Builder() method in v:0.0.9

### ISSUE THREAD

**Issue by ma7modGamel** [GeideaSolutions/Android-SDK#1]
How can I Fix it ?

**Comment by svkostadinoff** [comment]
`net.geidea.paymentsdk.flow.pay.PaymentData.Builder` is a class not a method. However, there are no changes to this builder. Could it be a Proguard issue? 
And please update to 2.0.0. This 0.0.9 is a very old one and some features might not work correctly with all the recent backend changes.
